# Package Build Configuration
name: PCK.AUTOMIC_DOCKER

source: ae

# binary object resource mapping will be defined here
# please add resources here
binaries:
  - object: RESOURCES/LIBS/PCK.AUTOMIC_DOCKER.PRV.STORE
    resources:
      - name: DOCKER 
        type: BINARY
        path: tools/target/docker-tool.jar
        version: 1.2.0